# Generated by Django 2.1.5 on 2019-02-20 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='manager',
        ),
    ]
