# Generated by Django 2.1.5 on 2019-02-11 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=5)),
                ('telegramID', models.CharField(max_length=20)),
                ('kakaoID', models.CharField(max_length=20, null=True)),
                ('lineID', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=20)),
                ('latitude', models.FloatField()),
                ('hardness', models.FloatField()),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-user_name',),
            },
        ),
        migrations.AddField(
            model_name='info',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_info.Profile'),
        ),
    ]
